// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: transfer_safe.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          int32                  `protobuf:"varint,1,opt,name=role,proto3" json:"role,omitempty"`
	TransData     string                 `protobuf:"bytes,2,opt,name=transData,proto3" json:"transData,omitempty"`
	EncryptData   string                 `protobuf:"bytes,3,opt,name=encryptData,proto3" json:"encryptData,omitempty"`
	DecryptData   string                 `protobuf:"bytes,4,opt,name=decryptData,proto3" json:"decryptData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_transfer_safe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_safe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_transfer_safe_proto_rawDescGZIP(), []int{0}
}

func (x *Data) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *Data) GetTransData() string {
	if x != nil {
		return x.TransData
	}
	return ""
}

func (x *Data) GetEncryptData() string {
	if x != nil {
		return x.EncryptData
	}
	return ""
}

func (x *Data) GetDecryptData() string {
	if x != nil {
		return x.DecryptData
	}
	return ""
}

type GetPublicTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          int32                  `protobuf:"varint,1,opt,name=role,proto3" json:"role,omitempty"` //"FRONT"前端, "BACKEND"服务端
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicTokenRequest) Reset() {
	*x = GetPublicTokenRequest{}
	mi := &file_transfer_safe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicTokenRequest) ProtoMessage() {}

func (x *GetPublicTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_safe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicTokenRequest.ProtoReflect.Descriptor instead.
func (*GetPublicTokenRequest) Descriptor() ([]byte, []int) {
	return file_transfer_safe_proto_rawDescGZIP(), []int{1}
}

func (x *GetPublicTokenRequest) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

type GetPrivateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          int32                  `protobuf:"varint,1,opt,name=role,proto3" json:"role,omitempty"` //"FRONT"前端, "BACKEND"服务端
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrivateTokenRequest) Reset() {
	*x = GetPrivateTokenRequest{}
	mi := &file_transfer_safe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrivateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivateTokenRequest) ProtoMessage() {}

func (x *GetPrivateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_safe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivateTokenRequest.ProtoReflect.Descriptor instead.
func (*GetPrivateTokenRequest) Descriptor() ([]byte, []int) {
	return file_transfer_safe_proto_rawDescGZIP(), []int{2}
}

func (x *GetPrivateTokenRequest) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

// The response message containing the greetings
type GetPublicTokenReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`      //公钥
	ErrCode       int32                  `protobuf:"varint,2,opt,name=errCode,proto3" json:"errCode,omitempty"` //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicTokenReply) Reset() {
	*x = GetPublicTokenReply{}
	mi := &file_transfer_safe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicTokenReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicTokenReply) ProtoMessage() {}

func (x *GetPublicTokenReply) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_safe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicTokenReply.ProtoReflect.Descriptor instead.
func (*GetPublicTokenReply) Descriptor() ([]byte, []int) {
	return file_transfer_safe_proto_rawDescGZIP(), []int{3}
}

func (x *GetPublicTokenReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetPublicTokenReply) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

type GetPrivateTokenReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` //密钥
	ErrCode       int32                  `protobuf:"varint,2,opt,name=errCode,proto3" json:"errCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrivateTokenReply) Reset() {
	*x = GetPrivateTokenReply{}
	mi := &file_transfer_safe_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrivateTokenReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivateTokenReply) ProtoMessage() {}

func (x *GetPrivateTokenReply) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_safe_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivateTokenReply.ProtoReflect.Descriptor instead.
func (*GetPrivateTokenReply) Descriptor() ([]byte, []int) {
	return file_transfer_safe_proto_rawDescGZIP(), []int{4}
}

func (x *GetPrivateTokenReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetPrivateTokenReply) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

var File_transfer_safe_proto protoreflect.FileDescriptor

const file_transfer_safe_proto_rawDesc = "" +
	"\n" +
	"\x13transfer_safe.proto\x12\rtransfer_safe\"|\n" +
	"\x04Data\x12\x12\n" +
	"\x04role\x18\x01 \x01(\x05R\x04role\x12\x1c\n" +
	"\ttransData\x18\x02 \x01(\tR\ttransData\x12 \n" +
	"\vencryptData\x18\x03 \x01(\tR\vencryptData\x12 \n" +
	"\vdecryptData\x18\x04 \x01(\tR\vdecryptData\"+\n" +
	"\x15GetPublicTokenRequest\x12\x12\n" +
	"\x04role\x18\x01 \x01(\x05R\x04role\",\n" +
	"\x16GetPrivateTokenRequest\x12\x12\n" +
	"\x04role\x18\x01 \x01(\x05R\x04role\"E\n" +
	"\x13GetPublicTokenReply\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x18\n" +
	"\aerrCode\x18\x02 \x01(\x05R\aerrCode\"F\n" +
	"\x14GetPrivateTokenReply\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x18\n" +
	"\aerrCode\x18\x02 \x01(\x05R\aerrCode2\xd9\x02\n" +
	"\fTransferSafe\x12e\n" +
	"\x17SecureTransferPublicKey\x12$.transfer_safe.GetPublicTokenRequest\x1a\".transfer_safe.GetPublicTokenReply\"\x00\x12h\n" +
	"\x18SecureTransferPrivateKey\x12%.transfer_safe.GetPrivateTokenRequest\x1a#.transfer_safe.GetPrivateTokenReply\"\x00\x12;\n" +
	"\rSecureEncrypt\x12\x13.transfer_safe.Data\x1a\x13.transfer_safe.Data\"\x00\x12;\n" +
	"\rSecureDecrypt\x12\x13.transfer_safe.Data\x1a\x13.transfer_safe.Data\"\x00B\x12Z\x10live_safty/protob\x06proto3"

var (
	file_transfer_safe_proto_rawDescOnce sync.Once
	file_transfer_safe_proto_rawDescData []byte
)

func file_transfer_safe_proto_rawDescGZIP() []byte {
	file_transfer_safe_proto_rawDescOnce.Do(func() {
		file_transfer_safe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transfer_safe_proto_rawDesc), len(file_transfer_safe_proto_rawDesc)))
	})
	return file_transfer_safe_proto_rawDescData
}

var file_transfer_safe_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_transfer_safe_proto_goTypes = []any{
	(*Data)(nil),                   // 0: transfer_safe.Data
	(*GetPublicTokenRequest)(nil),  // 1: transfer_safe.GetPublicTokenRequest
	(*GetPrivateTokenRequest)(nil), // 2: transfer_safe.GetPrivateTokenRequest
	(*GetPublicTokenReply)(nil),    // 3: transfer_safe.GetPublicTokenReply
	(*GetPrivateTokenReply)(nil),   // 4: transfer_safe.GetPrivateTokenReply
}
var file_transfer_safe_proto_depIdxs = []int32{
	1, // 0: transfer_safe.TransferSafe.SecureTransferPublicKey:input_type -> transfer_safe.GetPublicTokenRequest
	2, // 1: transfer_safe.TransferSafe.SecureTransferPrivateKey:input_type -> transfer_safe.GetPrivateTokenRequest
	0, // 2: transfer_safe.TransferSafe.SecureEncrypt:input_type -> transfer_safe.Data
	0, // 3: transfer_safe.TransferSafe.SecureDecrypt:input_type -> transfer_safe.Data
	3, // 4: transfer_safe.TransferSafe.SecureTransferPublicKey:output_type -> transfer_safe.GetPublicTokenReply
	4, // 5: transfer_safe.TransferSafe.SecureTransferPrivateKey:output_type -> transfer_safe.GetPrivateTokenReply
	0, // 6: transfer_safe.TransferSafe.SecureEncrypt:output_type -> transfer_safe.Data
	0, // 7: transfer_safe.TransferSafe.SecureDecrypt:output_type -> transfer_safe.Data
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transfer_safe_proto_init() }
func file_transfer_safe_proto_init() {
	if File_transfer_safe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transfer_safe_proto_rawDesc), len(file_transfer_safe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transfer_safe_proto_goTypes,
		DependencyIndexes: file_transfer_safe_proto_depIdxs,
		MessageInfos:      file_transfer_safe_proto_msgTypes,
	}.Build()
	File_transfer_safe_proto = out.File
	file_transfer_safe_proto_goTypes = nil
	file_transfer_safe_proto_depIdxs = nil
}
